# Generated by Django 3.0.1 on 2020-01-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('code', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True,null=True)),
                ('url', models.URLField(unique=True, verbose_name='url')),
            ],
        ),
    ]
