# Generated by Django 3.0.1 on 2020-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
